# Generated by Django 4.2.23 on 2025-07-17 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 17, 17, 0, 15, 505740, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
